markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: 
google_site_verification: 

repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

collections:
  docs:
    output: true

name: Test Jekyll • Nicolás Ardanz
description: Transform your plain text into static websites and blogs
url: https://jekyllrb.com
avatar: https://avatars1.githubusercontent.com/u/9165711?v=3&s=460

twitter:
  username: nardanz
facebook:
  username: nicolas.ardanz
github:
  username: nardanz
Google+:
  username: nardanz
  
logo: img/logo-2x.png

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions
